name = "telegram-connector-example"
main = "bot.ts"
compatibility_date = "2024-01-01"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# Uncomment and configure if using D1
# [[d1_databases]]
# binding = "DB"
# database_name = "telegram-bot-db"
# database_id = "your-database-id"

# Uncomment and configure if using KV
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"