name = "telegram-bot-example"
main = "bot.ts"
compatibility_date = "2024-01-01"
node_compat = true

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "KV_CACHE"
id = "your-kv-namespace-id"

[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "your-sessions-namespace-id"

[[kv_namespaces]]
binding = "STARS_STORE"
id = "your-stars-namespace-id"

# D1 Database (optional)
[[d1_databases]]
binding = "DB"
database_name = "telegram-bot-db"
database_id = "your-database-id"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
[vars]
ENVIRONMENT = "production"
BOT_NAME = "My Telegram Bot"
LOG_LEVEL = "info"

# Routes
[[routes]]
pattern = "your-domain.com/telegram-webhook"
zone_name = "your-domain.com"

# Secrets (set via wrangler secret put COMMAND_NAME)
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_WEBHOOK_SECRET
# wrangler secret put ADMIN_USER_ID
# wrangler secret put GEMINI_API_KEY