name = "my-telegram-bot"
main = "bot.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Basic configuration
[vars]
ENVIRONMENT = "development"
CLOUD_PLATFORM = "cloudflare"

# D1 Database (create with: wrangler d1 create my-bot-db)
[[d1_databases]]
binding = "DB"
database_name = "my-bot-db"
database_id = "your-database-id-here"

# KV Namespaces (create with: wrangler kv:namespace create <name>)
[[kv_namespaces]]
binding = "CACHE"
id = "your-cache-namespace-id"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-rate-limit-namespace-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-namespace-id"

# Production environment
[env.production]
name = "my-telegram-bot-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "my-bot-db-prod"
database_id = "your-prod-database-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-prod-cache-namespace-id"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-prod-rate-limit-namespace-id"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-prod-sessions-namespace-id"